version: '1.0.2'
services:
  bot:
    container_name: 'DM-Spammer-Bot'
    build:
      context: .
    stop_signal: SIGINT
    restart: unless-stopped
    command: "python3 main.py"
    volumes:
      - .:/app
      
      